### ISSUE TITLE
itu learnit -reset doesn't reset

### ISSUE THREAD

**Issue by magnuswurtz** [AsgereDreemurr/CLI-ITU#48]
The -reset flag doesn't reset but instead fuzzy searches for "-reset" and opens the corresponding page on learnit

**Comment by AsgereDreemurr** [comment]
The config can be reset using the following commands
- `itu learnit --reset`
- `itu learnit -r`

I noticed the documentation wrongly suggested to use `itu learnit -reset`. My latest commit resolves this.
